id: opecha:P002931
initial_creation_type: ocr
source_metadata:
  id: bdr:W29114
  title: དཔལ་ཧེ་རུ་ཀ་ཀུན་བཟང་གང་ཤར་དབང་པོ་འཇིགས་མེད་ཕྱོགས་ལས་རྣམ་པར་རྒྱལ་བའི་རྟོགས་བརྗོད་ནོར་བུ་རིན་པོ་ཆེ་ཡིད་བཞིན་དབང་གི་རྒྱལ་པོ
  volume: ''
  author: ''
