id: IDB549BDB
legacy_id: P002931
ocr_import_info:
  bdrc_scan_id: W29114
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T00:00:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:48:35.561386+00:00'
last_modified: 2022-09-02 17:49:23.767462
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29114
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29114
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གང་ཤར་དབང་པོའི་རྣམ་ཐར།
  author: ཀརྨ་བཤད་སྒྲུབ་ཕྲིན་ལས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9758366124200163
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1GS105494:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS105494
      total_pages: 436
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS105494.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9758366124200163
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
